// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lddftkbniprmmorgmttq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZGZ0a2JuaXBybW1vcmdtdHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODAzMDcsImV4cCI6MjA2Mzc1NjMwN30.janpKc2nqmMwKsFp0t9lLYJS3AggKTLN5Ni79x11EjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);